"""
Data models for Kalam CX.

These models define the shape of data as it moves through the pipeline:

    Call Transcript -> Customer Data -> Handbook Rules
        -> AI Documentation Draft -> Grounding & Safety Result
        -> Decision Result -> Final Record -> Operational Summary

This file only defines data structures (schemas). It does not contain any
business logic, AI logic, or validation logic. See docs/Data_Schema.md for
the full field descriptions.
"""

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# 1. Call Transcript
# ---------------------------------------------------------------------------
class CallTranscript(BaseModel):
    """The transcribed conversation between the customer and the agent."""

    call_id: str
    customer_id: Optional[str] = None
    transcript: str
    timestamp: str = ""
    channel: str = ""


# ---------------------------------------------------------------------------
# 2. Customer Data
# ---------------------------------------------------------------------------
class CustomerData(BaseModel):
    """Customer information retrieved using the customer ID."""

    customer_id: str
    name: str
    client: str = ""
    tier: str = ""
    phone: str = ""
    account_tier: str = ""
    account_status: str = ""
    previous_tickets: List[Dict] = Field(default_factory=list)
    open_tickets: List[Dict] = Field(default_factory=list)

    @property
    def has_open_tickets(self) -> bool:
        return len(self.open_tickets) > 0 or len(self.previous_tickets) > 0

    @property
    def is_priority_tier(self) -> bool:
        current_tier = self.tier or self.account_tier
        return current_tier == "priority"

# ---------------------------------------------------------------------------
# 3. Handbook Rule
# ---------------------------------------------------------------------------
class HandbookRule(BaseModel):
    """A rule retrieved from the support handbook."""

    rule_id: str
    section: str = ""
    category: str = ""
    subcategory: str = ""
    disposition: str = ""
    priority: str = ""
    sentiment: str = ""
    escalation_required: bool = False
    keywords: List[str] = Field(default_factory=list)
    conditions: Dict = Field(default_factory=dict)
    rule_text: str = ""


# ---------------------------------------------------------------------------
# 4. AI Documentation Draft
# ---------------------------------------------------------------------------
class AIDocumentationDraft(BaseModel):
    """The structured draft record generated by the AI Documentation Engine.

    This is a draft only. It must pass validation before becoming a
    Final Record.
    """

    category: str
    subcategory: str = "not stated"
    disposition: str
    priority: str
    sentiment: str
    summary: str
    resolution: str
    next_action: str
    escalation_reason: Optional[str] = None
    rule_references: List[str] = Field(default_factory=list)
    grounding: Dict[str, str] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# 5. Grounding & Safety Result
# ---------------------------------------------------------------------------
class GroundingSafetyResult(BaseModel):
    """Results of validation performed on the AI-generated draft."""

    grounded: bool
    unsupported_fields: List[str] = Field(default_factory=list)
    sensitive_data_detected: bool
    ambiguity_detected: bool
    escalation_triggered: bool
    caller_instruction_ignored: bool = False
    validation_errors: List[str] = Field(default_factory=list)
    field_evidence: Dict[str, str] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# 6. Decision Result
# ---------------------------------------------------------------------------
class DecisionType(str, Enum):
    """The possible deterministic decisions made by the application."""

    AUTO_SAVE = "AUTO_SAVE"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    ESCALATE = "ESCALATE"
    NON_INTERACTION = "NON_INTERACTION"

class DecisionResult(BaseModel):
    """The deterministic decision made by the application for a call."""

    decision: DecisionType
    reason: str
    review_required: bool
    escalation_required: bool
    next_actions: List[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# 7. Final Record
# ---------------------------------------------------------------------------
class RecordStatus(str, Enum):
    """The possible status values for a Final Record."""

    AUTO_SAVED = "AUTO_SAVED"
    APPROVED = "APPROVED"
    ESCALATED = "ESCALATED"


class FinalRecord(BaseModel):
    """The approved or automatically saved documentation record."""

    record_id: str
    call_id: str
    customer_id: Optional[str]
    customer_name: str = ""
    client: str = ""
    tier: str = ""
    category: str
    subcategory: str
    disposition: str
    priority: str
    sentiment: str
    summary: str
    resolution: str
    next_action: str
    status: RecordStatus
    decision: DecisionType
    escalation_reason: Optional[str] = None
    rule_references: List[str] = Field(default_factory=list)
    grounding: Dict[str, str] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# 8. Operational Summary
# ---------------------------------------------------------------------------
class OperationalSummary(BaseModel):
    """Basic operational metrics from processed calls."""

    total_calls: int
    auto_saved: int
    human_review: int
    escalated: int
    non_interactions: int
    categories: Dict[str, int] = Field(default_factory=dict)
    sentiments: Dict[str, int] = Field(default_factory=dict)
